Generate Reliably CI/CD workflow
reliablyhq/documentation pull request #120
Opened 2021-02-11 08:58 UTC by dmartin35

2021-02-11 09:28 UTC, xaah approved these changes
Looks good!

2021-02-11 13:06 UTC, mperrien requested changes
The content is great, and I really like the CLI flow.

I just made a few wording corrections.

2021-02-12 09:29 UTC, dmartin35 commented on docs/getting-started/ci-workflow/index.md
> +? Select your CI/CD platform to create the Reliably workflow ?  [Use arrows to move, type to filter]
Good remark, I updated the doc, and I'll make the change in the CLI as well
However , I cannot removes the leading question mark, it's rendered by the interactive library that we're using

2021-02-12 09:31 UTC, dmartin35 commented
FYI, I have made the changes @mperrien

2021-02-19 15:01 UTC, merged