added docs for slack criteria creation
reliablyhq/documentation pull request #297
Opened 2021-06-28 13:15 UTC by mick-roper

* added a page to describe Slack Alert fucntionality

2021-06-28 14:44 UTC, mperrien commented
@mick-roper I fixed a few typos, and I have a couple of questions/remarks:

- what is the format of the `ChannelURL`? For the "Reliably Team" Slack channel, is it `reliablyteam` or `reliably.slack.com`? I think we should be explicit about it.
- we could also provide an example of the `MessageTemplate`, I guess.

In the Properties section, there are two links for **Selectors** and **ObjectiveResult**, but there linking to `/`. Where should those go?

Also, I'm wondering if this should go in the **How it works** section, or if we should create an **Integrations** sub-section of the Guides.

2021-07-22 20:10 UTC, Lawouach requested changes
Just wondered if that one was ready?

2021-07-22 20:10 UTC, Lawouach commented on docs/guides/how-it-works/slack-alerts/index.md
> +    Window: 1h
we need to make these lower case

2021-07-22 20:10 UTC, Lawouach commented on docs/guides/how-it-works/slack-alerts/index.md
> +    RemainingPercentThreshold: 1
likewise

2021-07-23 10:46 UTC, mick-roper commented on docs/guides/how-it-works/slack-alerts/index.md
> +    RemainingPercentThreshold: 1
done

2021-07-23 10:46 UTC, mick-roper commented on docs/guides/how-it-works/slack-alerts/index.md
> +    Window: 1h
done

2021-07-23 10:51 UTC, ciaranevans requested changes

2021-07-23 10:51 UTC, ciaranevans commented on docs/guides/how-it-works/slack-alerts/index.md
> +Reliably supports integration with Slack. It is possible to configure Realibly to send a message to Slack when the budget for a given objective is less than the threshold set in the alert configurati
```suggestion
Reliably supports integration with Slack. It is possible to configure Reliably to send a message to Slack when the budget for a given objective is less than the threshold set in the alert configuration.
```

2021-07-23 10:51 UTC, ciaranevans commented on docs/reference/entities/slackalertcriteria.md
> +An `SlackAlertCrtieria` declaratively defines the data required to send a message to a Slack channel, and the conditions required for the criteria to be used.
```suggestion
A `SlackAlertCrtieria` declaratively defines the data required to send a message to a Slack channel, and the conditions required for the criteria to be used.
```

This ones pedantic of me

2021-07-23 10:51 UTC, ciaranevans commented on docs/reference/entities/slackalertcriteria.md
> +apiVersion: reliablyhq.com/v1
```suggestion
apiVersion: reliably.com/v1
```

2021-07-23 11:58 UTC, ciaranevans approved these changes

2021-07-23 11:58 UTC, merged