slo doc
reliablyhq/documentation pull request #317
Opened 2021-07-20 15:20 UTC by xaah

- slo page start
- tabs and aws
- slo doc added

2021-07-20 15:38 UTC, ciaranevans commented
@xaah the selection on the left hand side looks funky to me:
![image](https://user-images.githubusercontent.com/9111975/126353409-302a5f66-b550-4897-b9fd-be336e51fd56.png)

Running on Chrome on MacOS (I've moved the window around and resized it too)

2021-07-20 15:44 UTC, Lawouach requested changes
LGTM

Minor comments only :)

2021-07-20 15:44 UTC, Lawouach commented on docs/getting-started/slos/index.md
> +
These two are going to be common, maybe we could use an admonition block (tip or note) so that they are the same everywhere?

2021-07-20 15:44 UTC, Lawouach commented on docs/getting-started/slos/index.md
> +
I didn't remember that init didn't do the sync itself.

2021-07-20 15:44 UTC, Lawouach commented on docs/getting-started/slos/index.md
> +:::
s/you may not/you will not/

this is not an option IMO, if you use something we don't support, we can't use the agent on it (which is cool but need to be crystal clear)

2021-07-20 15:44 UTC, Lawouach commented on docs/getting-started/slos/index.md
> +:::note Note
seems to be an "Important" or "Warning"

2021-07-20 15:50 UTC, xaah commented
@ciaranevans yeah I was thinking of waiting for Marc for a change on that one but I'll see if I can modify without breaking other things.

2021-07-20 15:52 UTC, xaah commented on docs/getting-started/slos/index.md
> +
I was thinking a tip or note  of that size would be quite a loud start to a doc, and if it's to be used in many docs, then more so. WDYT? I could make it a reusable block though, without the color overlay?

2021-07-20 15:52 UTC, xaah commented on docs/getting-started/slos/index.md
> +
it was so a user could edit the manifest before syncing

2021-07-20 15:54 UTC, xaah commented on docs/getting-started/slos/index.md
> +:::
My thinking was that you could technically define an objective manually and it still be compatible with a data provider, and thus work with the agent. However, if that makes it confusing I can change to will not.

2021-07-20 15:57 UTC, xaah commented on docs/getting-started/slos/index.md
> +:::note Note
Good point I've changed to warning now

2021-07-20 16:17 UTC, xaah commented on docs/getting-started/slos/index.md
> +:::
Nevermind previous comment, I've changed to "will not" now

2021-07-21 09:03 UTC, xaah commented on docs/getting-started/slos/index.md
> +
With the "Before you begin"/"Prerequisites" section I think it's usually not inside a tip/note and may be confusing. Here are some examples:
https://support.snyk.io/hc/en-us/articles/360014875297-Getting-started-with-Snyk-Open-Source
https://cloud.google.com/run/docs/quickstarts/build-and-deploy/go

2021-07-21 09:09 UTC, Lawouach commented on docs/getting-started/slos/index.md
> +
That is good by me, jus as long as all pages have the same style/format approach, I'm open to anything.

2021-07-21 09:41 UTC, xaah commented on docs/getting-started/slos/index.md
> +
ok sounds good. I've create a `Setup` component that can be referenced in any doc with that content.

2021-07-21 09:42 UTC, xaah commented
@ciaranevans menu issue being looked at by @mperrien  in separate issue. https://github.com/reliablyhq/documentation/issues/319

2021-07-21 10:03 UTC, xaah commented on docs/getting-started/slos/index.md
> +
@Lawouach is this ok to resolve now?

2021-07-21 10:49 UTC, Lawouach commented
all good @xaah

2021-07-21 10:59 UTC, merged